services:
  - type: web
    name: cpp-test-prep
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --config gunicorn.conf.py app:app
    autoDeploy: true
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: OPENAI_CHAT_MODEL
        value: gpt-4o-mini
      - key: OPENAI_API_BASE
        value: https://api.openai.com/v1
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: WEB_CONCURRENCY
        value: "3"
  - type: web
    buildCommand: |
      pip install -r requirements.txt
      sed -i 's/\t/    /g' app.py
    startCommand: gunicorn app:app

