name: Smoke Test

on:
  push:
    branches: [ main ]           # if your default branch is "production", change to [ production ]
  pull_request:
    branches: [ main ]           # same note as above
  workflow_dispatch:             # adds a "Run workflow" button

jobs:
  smoke:
    name: Smoke Test
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run smoke test
        env:
          SECRET_KEY: test-secret
          OPENAI_API_KEY: dummy
        run: |
          python tests/smoke_test.py
